# Ansible-style inventory of the Waystar Royco fleet.
# Vinzenz uses this for ad-hoc admin tasks (`ansible all -m ping` etc.)

[web]
apache    ansible_host=10.40.0.2  ansible_user=vinzenz.fedora

[workstations]
john      ansible_host=10.30.0.5  ansible_user=vinzenz.fedora
luke      ansible_host=10.30.0.7  ansible_user=vinzenz.fedora

[databases]
db-internal ansible_host=10.30.0.6 ansible_user=postgres

[all:vars]
ansible_ssh_private_key_file=/home/vinzenz.fedora/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
